--CREATE DATABASE EDURVI
--USE EDURVI

CREATE TABLE USUARIOS(
ID INT IDENTITY(1000,1),
USUARIO VARCHAR(50),
CONTRASENIA VARBINARY(500)
)

CREATE PROC SP_AGREGARUSUARIO
@USUARIO VARCHAR(50),
@CONTRASENIA VARCHAR(50),
@PATRON VARCHAR(50)
AS
BEGIN
INSERT INTO USUARIOS(USUARIO, CONTRASENIA) VALUES (@USUARIO, ENCRYPTBYPASSPHRASE(@PATRON, @CONTRASENIA))
END


CREATE PROC SP_VALIDARUSUARIO
@USUARIO VARCHAR(50),
@CONTRASENIA VARCHAR(50),
@PATRON VARCHAR(50)
AS
BEGIN
SELECT * FROM USUARIOS WHERE USUARIO=@USUARIO AND CONVERT(varchar(50), DECRYPTBYPASSPHRASE(@PATRON, CONTRASENIA))= @CONTRASENIA
END

SELECT * FROM USUARIOS

SP_AGREGARUSUARIO 'Edurvi', 'fgdgd', 'edurviggez'
